import PDFDocument from 'pdfkit';
import { createServiceClient } from '@/lib/supabase/server';

export async function generatePDFReport(
  websiteId: string,
  dateFrom: string,
  dateTo: string
): Promise<Buffer> {
  const service = createServiceClient();

  const { data: website } = await service
    .from('websites')
    .select('domain, brand_name, visibility_score')
    .eq('id', websiteId)
    .single();

  const { data: audits } = await service
    .from('audits')
    .select('*')
    .eq('website_id', websiteId)
    .gte('created_at', dateFrom)
    .lte('created_at', dateTo)
    .order('created_at', { ascending: false });

  const { data: recs } = await service
    .from('recommendations')
    .select('*')
    .eq('website_id', websiteId)
    .order('impact_score', { ascending: false })
    .limit(5);

  const doc = new PDFDocument({ margin: 50 });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk) => chunks.push(chunk));
  doc.on('end', () => {});

  // Header
  doc
    .rect(0, 0, doc.page.width, 100)
    .fill('#6366f1');
  doc
    .fillColor('#ffffff')
    .fontSize(24)
    .text('Sightura', 50, 30);
  doc
    .fontSize(14)
    .text('AI Visibility Report', 50, 60);

  doc.moveDown(4);
  doc.fillColor('#0f172a');

  // Website info
  doc.fontSize(16).text(`Website: ${website?.brand_name || website?.domain}`);
  doc
    .fontSize(12)
    .fillColor('#64748b')
    .text(`Domain: ${website?.domain}`);
  doc.text(`Period: ${dateFrom} → ${dateTo}`);
  doc.text(`Visibility Score: ${website?.visibility_score ?? 'N/A'}`);

  doc.moveDown(1);

  // Audit summary
  doc.fontSize(14).fillColor('#0f172a').text('Audit History');
  doc.moveDown(0.5);
  audits?.forEach((a: any) => {
    doc
      .fontSize(11)
      .text(
        `${a.created_at.slice(0, 10)} | Type: ${a.audit_type} | Score: ${a.visibility_score} | Queries: ${a.queries_consumed}`
      );
  });

  doc.moveDown(1);

  // Recommendations
  doc.fontSize(14).text('Top Recommendations');
  doc.moveDown(0.5);
  recs?.forEach((r: any) => {
    doc
      .fontSize(11)
      .text(`• ${r.title} (Priority: ${r.priority}, Impact: ${r.impact_score}/10)`);
    if (r.fix_code) {
      doc
        .fontSize(9)
        .fillColor('#475569')
        .text(r.fix_code.substring(0, 200) + '...', { width: 400 });
    }
  });

  doc.moveDown(1);
  doc
    .fillColor('#94a3b8')
    .fontSize(8)
    .text('Generated by Sightura – AI Search Visibility Platform');

  doc.end();

  // Wait for the stream to finish
  return new Promise((resolve) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
  });
}